name = "SourceConcat"
uuid = "8d98e93c-9d9e-4165-b32a-ac5ad0c25aba"
version = "0.0.1"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Dates = "1.11.0"
Glob = "1.3.1"
InteractiveUtils = "1.11.0"
JSON3 = "1.14.3"
Printf = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
